export const LINKS = [
  { href: '/components', display: 'Components - section02' },
  { href: '/countup', display: 'Count up - section03' },
  { href: '/text', display: 'Text - section04' },
  { href: '/input', display: 'Input - section05' },
  { href: '/background', display: 'Background - section06' },
  { href: '/feedback', display: 'Feedback - section07' },
  { href: '/temperature', display: 'Temperature - section08' },
  { href: '/quiz', display: 'Quiz - section09' },
  { href: '/timer', display: 'Timer - section10' },
  { href: '/famous-saying', display: 'Famous Saying - section11' },
  { href: '/traffic-light', display: 'Traffic Light - section12' },
  { href: '/stopwatch', display: 'Stopwatch - section13' },
  { href: '/starwars', display: 'Star Wars - section14' },
  { href: '/pokemon', display: 'Pokemon - section15' },
  { href: '/memo', display: 'Memo - section16' },
];
