import type { Metadata } from 'next';
import { Inter, Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import Footer from '@/app/_components/Footer';

type Props = Readonly<{
  children: React.ReactNode;
}>;

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'udemy-react-chart-app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ja">
      <body className={`${inter.variable} ${notoSansJP.variable} antialiased font-sans`}>
        <div className="flex flex-col max-h-screen p-6 space-y-6">
          <header className="h-16 border-b pb-2">
            <h1 className="text-4xl font-bold">udemy-react-chart-app</h1>
          </header>
          <main className="flex-1">{children}</main>
          <footer className="h-16 border-t pt-2">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
